version: "3"
name: sparks-dev
services:

  nginx:
    container_name: nginx
    hostname: nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: dev.dockerfile
      context: ./nginx
    ports:
      - "80:80"
    links:
      - api
      - client

  client:
    container_name: client
    hostname: client
    build:
      dockerfile: dev.dockerfile
      context: ./client
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - api
    volumes:
      - ./client:/workspaces/client
    stdin_open: true
    tty: true

  api:
    container_name: api
    hostname: api
    restart: always
    build:
      dockerfile: dev.dockerfile
      context: ./api
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./api:/workspaces/api

  mongo:
    image: mongo:7.0.2
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: base
      MONGO_USER: devuser
      MONGO_PASSWORD: devpass
      MONGO_DB_BASE_NAME: base
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - sparks-mongodb-data:/data/db

volumes:
  sparks-mongodb-data: