version: "2"
services:

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    links:
      - api
      - client

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - api
    volumes:
      - type: bind
        source: ./client
        target: /client
    stdin_open: true
    tty: true

  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./api
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - type: bind
        source: ./api
        target: /api